env:
  TERM: alacritty

shell:
  program: tmux
  args:
   - new
   - -A
   - -s main

hide_cursor_when_typing: true

font:
  size: 14.0
  normal:
    family: FiraCode Nerd Font
    style: Retina

  bold:
    family: FiraCode Nerd Font
    style: Bold
#   bold:
#     family: SF Mono
#     style: Bold

#   italic:
#     family: SF Mono
#     style: Italic

# Colors (Base16 Default Dark)
colors:
  # Default colors
  primary:
    background: '#181818'
    foreground: '#d8d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '#d8d8d8'
    cursor: '#d8d8d8'

  # Normal colors
  normal:
    black:   '#181818'
    red:     '#ab4642'
    green:   '#a1b56c'
    yellow:  '#f7ca88'
    blue:    '#7cafc2'
    magenta: '#ba8baf'
    cyan:    '#86c1b9'
    white:   '#d8d8d8'

  # Bright colors
  bright:
    black:   '#585858'
    red:     '#ab4642'
    green:   '#a1b56c'
    yellow:  '#f7ca88'
    blue:    '#7cafc2'
    magenta: '#ba8baf'
    cyan:    '#86c1b9'
    white:   '#f8f8f8'

# Setup some amazing custom key bindings here - Best thing is you can setup key bindings
# using Mac's 'command' to control your tmux.
# A great reference: https://arslan.io/2018/02/05/gpu-accelerated-terminal-alacritty/#make-alacritty-feel-like-iterm2
key_bindings:
  # remove the line below!
  - { key: W, mods: Command, action: Quit }
  # Use command + [ - to go to previous tmux window
  - { key: LBracket, mods: Command, chars: "\x5c\x70" }
  # Use command + ] - to go to previous tmux window
  - { key: RBracket, mods: Command, chars: "\x5c\x6e" }
  # ctrl-^ doesn't work in some terminals like alacritty
  - { key: Key6, mods: Control, chars: "\x1e" }
  - { key: D,     mods: Command,       chars: "\x06\x76" }
  - { key: D,     mods: Command|Shift, chars: "\x06\x73" }
