;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        crux-move-beginning-of-line
        indent-for-tab-command
        kill-region
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        compose-mail
        counsel-M-x
        swiper-mc
        ))
