;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        asm-comment
        c-electric-brace
        c-electric-colon
        c-electric-delete-forward
        c-electric-paren
        c-electric-semi&comma
        c-electric-star
        c-indent-line-or-region
        crux-move-beginning-of-line
        electric-newline-and-maybe-indent
        indent-for-tab-command
        kill-region
        mark-word
        sp-backward-delete-char
        sp-backward-kill-word
        sp-delete-char
        sp-splice-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        compose-mail
        counsel-M-x
        swiper-mc
        ))
